# theme: jekyll-theme-tactile
# remote_theme: yizeng/jekyll-theme-simple-texture
remote_theme: broccolini/swiss
theme_color: white
# etc
title: Live Work Work Work Die
description: A bold typographic theme inspired by Swiss design.
